apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.6/manifests/install.yaml
- base/argo-cd-ui-ingress.yaml
