apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp1-eks2
  namespace: argocd
spec:
  project: default
  
  source:
    path: apps/app1
    repoURL: https://github.com/matanmiz1/argocd-apps.git
    targetRevision: HEAD
  destination:
    name: ie-test-eks2
    namespace: myapps
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
