apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mychart-app1
  namespace: argocd
spec:
  project: default

  source:
    path: helm/mychart
    repoURL: https://github.com/matanmiz1/argocd-apps.git
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: myapps

  helm:
    values:
      data: "Synced by ArgoCD"

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
