apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: a1
  namespace: argocd
spec:
  project: default

  source:
    path: apps/app1
    repoURL: https://github.com/matanmiz1/argocd-apps.git
    targetRevision: HEAD
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: myapps

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
