apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medapp
  namespace: argocd
spec:
  project: default

  source:
    path: medapp/regionA
    repoURL: https://github.com/matanmiz1/argocd-apps.git
    targetRevision: medapp-demo
    kustomize:
      patches:
        - target:
            kind: Deployment
            name: nginx-deployment
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/image
              value: 883241448326.dkr.ecr.eu-west-1.amazonaws.com/matan-argocd/${ARGOCD_APP_REVISION_SHORT}
      commonAnnotationsEnvsubst: true
      commonAnnotations:
        app-source-matan: ${ARGOCD_APP_NAME}
        version: ${ARGOCD_APP_REVISION_SHORT}
      # images:
      #   - 883241448326.dkr.ecr.eu-west-1.amazonaws.com/matan-argocd/${ARGOCD_APP_REVISION_SHORT}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: medapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
